// todo: comment this stuff and all html etc.
// noinspection JSUnresolvedVariable

const fs = require('fs');

const { DateTime } = require('luxon');

const express = require('express');
const app = express();

const helpers = require('./helperFunctions.js');

app.use(express.static('client'));
app.use(express.json());

app.route('/cards(/:id(\\d+))?')
  .get((req, res) => {
    const reqParamId = req.params.id;
    const reqQueryIds = req.query.ids;
    const cards = require('./serverdb.json').cards;
    // console.log(DateTime.fromISO(JSON.parse(JSON.stringify('2021-12-13T22:16:28.278Z'))));
    // todo: convert time to browser local time objects on client side?
    res.send(helpers.handleIdUrl(cards, reqParamId, reqQueryIds));
  })
  .post((req, res) => {
    fs.readFile('./serverdb.json', 'utf8', (err, data) => {
      if (err) {
        console.error(err);
      } else {
        const jsonData = JSON.parse(data);

        const newCard = req.body;
        if (jsonData.cards.length > 0) {
          // why does .at(-1) not work?!
          newCard.id = jsonData.cards[jsonData.cards.length - 1].id + 1; // new ID generated by adding 1 to final element in current cards list
        } else {
          newCard.id = 0;
        }
        newCard.time = DateTime.now().toUTC();
        jsonData.cards.push(newCard);

        const jsonString = JSON.stringify(jsonData, null, 2);
        fs.writeFile('./serverdb.json', jsonString, 'utf-8', () => {
          res.status(201);
          res.send();
        });
      }
    });
  });

app.route('/comments(/:id(\\d+))?')
  .get((req, res) => {
    const reqParamId = req.params.id;
    const reqQueryIds = req.query.ids;
    const comments = require('./serverdb.json').comments;
    res.send(helpers.handleIdUrl(comments, reqParamId, reqQueryIds));
  })
  .post((req, res) => {
    res.send('Comment POST');
  });

module.exports = app;
