const fetch = require('node-fetch');

/**
 * @param {Object[]} array
 * @param {Number[]} ids
 * @return {Object[]}
 */
module.exports.search = function (array, ids) {
  const results = [];
  for (const item of array) {
    if (ids.includes(item.id)) {
      results.push(item);
    }
  }
  return results;
};

/**
 * @param {Object[]} toSearch
 * @param {String} paramId
 * @param {String} queryIds
 * @return {Object[]}
 */
module.exports.handleIdUrl = function (toSearch, paramId, queryIds) {
  if (paramId !== undefined) {
    const paramIdNum = Number(paramId);
    return module.exports.search(toSearch, [paramIdNum]);
  } else if (queryIds) {
    const commaSplitRegexp = /, */;
    const queryIdsArray = queryIds.split(commaSplitRegexp).map((s) => Number(s));
    return module.exports.search(toSearch, queryIdsArray);
  } else {
    return toSearch;
  }
};

/**
 * @param {String} redditUrl
 * @return {Object|undefined}
 */
module.exports.getRedditData = async function (redditUrl) {
  const redditJSONUrl = redditUrl + '.json';
  const redditResponse = await fetch(redditJSONUrl);
  const redditJSON = await redditResponse.json();
  if (!redditJSON.error) {
    return redditJSON[1].data.children[0].data;
  } else {
    return undefined;
  }
};

module.exports.updateCardRedditData = function (cardObj, newRedditData) {
  cardObj.redditData = (({ score, author }) => ({
    score,
    author
  }))(newRedditData);

  if (newRedditData.replies !== '') {
    cardObj.redditData.numSubComments = newRedditData.replies.data.children.length;
  } else {
    cardObj.redditData.numSubComments = 0;
  }
};

module.exports.getNewValidId = function (currentArray) {
  if (currentArray.length > 0) {
    const usedIds = currentArray.map(e => e.id);
    return Math.max(...usedIds) + 1; // new ID generated by adding 1 to max element in current cards list
  } else {
    return 0;
  }
};
